- name: docker build and push
  hosts: 143.244.138.69  # Replace with the hostname or IP address of your target server
  become: yes  # Run tasks with sudo privileges

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes   

    - name: Build Docker Image
      command: docker build -t petstore .
      args:
        chdir: /var/lib/jenkins/workspace/petstore

    - name: tag image
      command: docker tag petstore:latest manideepm777/petstore:latest 

    - name: Log in to Docker Hub
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: manideepm777
        password: Qwerty@9999

    - name: Push image
      command: docker push manideepm777/petstore:latest

    - name: Run container
      command: docker run -d --name pet1 -p 8081:8080 manideepm777/petstore:latest
